package org.sgl.orc.models;

public enum tipoModalidade {
APRENDIZAGEM_BÁSICA,
APRENDIZAGEM_TÉCNICA,
HAB_TEC_PAGO,
HAB_TEC_GRATUITA,
HAB_TEC_EAD_GRATUITO,
HAB_TEC_EAD_PAGO,
QUALIFICACAO_GRATUITO,
QUALIFICACAO_EAD_GRATUITO,
QUALIFICACAO_EAD_PAGO,
QUALIFICACAO_PAGO,
APERFEICOAMENTO_EAD_GRATUITO,
APERFEICOAMENTO_EAD_PAGO,
APERFEICOAMENTO_PAGO,
APERFEICOAMENTO_GRATUITO,
INICIACAO_PROFISSIONAL_NEM,
INICIACAO_PAGO,
INICIACAO_EAD_PAGO,
INICIACAO_EAD_GRATUITO,
INICIACAO_GRATUITO,

}
