package org.sgl.orc.models.tipos;

public enum tipoModalidade {
APRENDIZAGEM_BÁSICA_GRATUITO,
APRENDIZAGEM_TÉCNICA_GRATUITO,
APERFEICOAMENTO_EAD_GRATUITO,
APERFEICOAMENTO_GRATUITO,
HAB_TEC_GRATUITO,
HAB_TEC_EBEP_GRATUITO,
HAB_TEC_EAD_GRATUITO,
INICIACAO_NEM_GRATUITO,
INICIACAO_GRATUITO,
INICIACAO_EAD_GRATUITO,
QUALIFICACAO_GRATUITO,
QUALIFICACAO_EAD_GRATUITO,
APERFEICOAMENTO_EAD_PAGO,
APERFEICOAMENTO_PAGO,
HAB_TEC_PAGO,
HAB_TEC_EAD_PAGO,
INICIACAO_PAGO,
INICIACAO_EAD_PAGO,
INICIACAO_EAD_BOLSAS_PAGO,
QUALIFICACAO_PAGO,
QUALIFICACAO_EAD_PAGO
}
